# Backup this file and rename it to config.toml
[mcp]
name = "Kopilot"

[server.llm]
model_provider = ""
base_url = ""
api_key = ""
model = ""
temperature = 0

[client.llm]
model_provider = ""
base_url = ""
api_key = ""
model = ""
temperature = 0

[kubernetes]
kubeconfig = ""
